version: '2'

services:
  _base:
    image: node:7.5.0
    volumes:
      - .:/app
    working_dir: /app
    env_file: ./config/environment.env

  app:
    extends:
      service: _base
    command: sh ./run.sh
    depends_on:
      - mysql
    ports:
      - "8000:8000"

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: mysql_pass
