version: '2'

services:
  _base:
    image: node:7.5.0
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/app
    working_dir: /app
    environment:
      PORT: 8000

  api:
    extends:
      service: _base
    command: npm start
    ports:
      - "8000:8000"
